### ISSUE TITLE
Latency too big

### ISSUE THREAD

**Issue by paul-at** [alexmacrae/SamplerBox_backup#1]
http://www.samplerbox.org/forum/304
I measured ~80ms as well

**Comment by alexmacrae** [comment]
@paul-at is this when using the on-board DAC (bcm2835)? I too have not been able to get much lower than 80ms without compromising quality using the RPi3's on-board audio. In `modules/sound.py` I force `sounddevice`'s latency to to be `high`:
[https://github.com/alexmacrae/SamplerBox/blob/master/modules/sound.py#L361](url)

When using one of my other external USB DACs I can get <15ms (the script reports ~8ms, but I'd say it's a bit more than that) because `sounddevice` is able to use the `latency='low'` option. Tested with a USB DAC PCM2704, Focusrite Scarlett 2i2, and PreSonus AudioBox iOne.

**Comment by paul-at** [comment]
I define latency as time between end of MIDI message and start of sound playing using our board I2S DAC. I use serial MIDI for this measurement because its easier to capture and there is less space for variability of results.

I just redone the measurement using RPi3 and 'official' SamplerBox code and its about 60ms.

However, don't know how you achieved it, but when I do same measurement using latest commit of your fork its only 8ms!! I think we can safely close this issue and post details on the website.

Here's a proof:
![ds1z_quickprint1](https://cloud.githubusercontent.com/assets/1401984/25642293/9894b1c6-2fa1-11e7-8ade-ca94990d214e.png)
