### ISSUE TITLE
Garbage characters appear on LCD (HD44780) after programmatic restart

### ISSUE THREAD

**Issue by alexmacrae** [alexmacrae/SamplerBox_backup#6]
When restarting the main `samplerbox.py` script, garbage characters appear and will not clear even after `GPIO.cleanup()` is called during a KeyboardInterrupt exception, and `RPLCD.CharLCD` is initialized during the restart. 

The bug does not occur every time. It seems to be _more likely_ to occur when the system is busy, eg loading samples, however it can still occur any time SamplerBox is restarted.

It will **not** occur if:
- the Raspberry Pi is powered off and on
- 5V power to the LCD is disconnected and reconnected (ie physically resetting the module)

I _suspect_ this may have something to do with the application being multithreaded but I haven't been able to determine this as a factor.

![img_20170502_014913](https://cloud.githubusercontent.com/assets/1542186/25584551/dc815f92-2ed9-11e7-83fb-91e3ad93b09d.jpg)

**Comment by paul-at** [comment]
Haven't noticed this with the LCD I use. Two ideas:
1. sampler box is stopped between sending half-bytes to LCD mixing up data processing in controller IC
2. I observed very similar bug when having LCD input voltage below the spec

**Comment by tokenterprises** [comment]
My keyboard is stashed away right now, and it is a pain to break open and access the Pi, so I can't give you the code I used, but you can figure it out when I tell you what I did to manage this. I use the 20x4 LCD and had to change the code anyways, so this came naturally when changing the code. First, I made sure every time there was a write command to the screen, I had every character sent for that line, so even if there were only needed four characters, the other 16 spaces were always sent to the screen. Next, I had all four lines refreshed anytime a new write command was sent to the screen, so even if only one line had new information, the entire screen would re-write, but I didn't clear it first, I think because of the delay this caused. This allows me to press the menu button and refresh the entire screen. And in all reality, you don't need to read the screen very often, unless you put some sort of feedback data in the stream.

As to why this happens, I know in my case it would happen only after the unit was sitting idle for an extended period of time, so I think it has to do with a 'hiccup' with the Pi. It also happens when I press a button 'half-assed' and it doesn't register correctly. Again, these seldom happen, but when they do it is really annoying to have a distorted screen, hence why I made the quick fix. Since I have been gigging with the unit, it hasn't happened once, but as mentioned, it would only happen when the unit sat idle for three hours or longer, and not necessarily every time.

**Comment by alexmacrae** [comment]
It appears that `lcd.clear()` doesn't actually properly clear the display. So instead at the beginning of the script I send blank characters to every character space, and this seems to solve the issue - even when the script is exited before a `GPIO.cleanup()`. Garbage characters were appearing when `GPIO.cleanup()` wasn't called, although not always the case.

@paul-at I think you're right re: half-bytes

Thanks @tokenterprises - you gave me the "send all characters" idea. However I don't need to send all characters for every change. It's only needed when initializing.
